version: '3.4'

services:
  telegramforwarding:
    image: telegramforwarding
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./config:/app/config
    env_file:
      - telegram-api.env